<?xml version="1.0" encoding="US-ASCII"?>


<!--
	Bayesian network in XMLBIF v0.3 (BayesNet Interchange Format)
	Produced by JavaBayes (http://www.cs.cmu.edu/~javabayes/
	Output created Tue May 02 16:32:10 CDT 2000
-->



<!-- DTD for the XMLBIF 0.3 format -->
<!DOCTYPE BIF [
	<!ELEMENT BIF ( NETWORK )*>
		<!ATTLIST BIF VERSION CDATA #REQUIRED>
	<!ELEMENT NETWORK ( NAME, ( PROPERTY | VARIABLE | DEFINITION )*)>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT VARIABLE ( NAME, ( OUTCOME |  PROPERTY )* ) >
		<!ATTLIST VARIABLE TYPE (nature|decision|utility) "nature">
	<!ELEMENT OUTCOME (#PCDATA)>
	<!ELEMENT DEFINITION ( FOR | GIVEN | TABLE | PROPERTY )* >
	<!ELEMENT FOR (#PCDATA)>
	<!ELEMENT GIVEN (#PCDATA)>
	<!ELEMENT TABLE (#PCDATA)>
	<!ELEMENT PROPERTY (#PCDATA)>
]>


<BIF VERSION="0.3">
<NETWORK>
<NAME>InternalNetwork</NAME>

<!-- Variables -->
<VARIABLE TYPE="nature">
	<NAME>VisitAsia</NAME>
	<OUTCOME>Visit</OUTCOME>
	<OUTCOME>No_Visit</OUTCOME>
	<PROPERTY>position = (166, 79)</PROPERTY>
</VARIABLE>

<VARIABLE TYPE="nature">
	<NAME>Smoking</NAME>
	<OUTCOME>Smoker</OUTCOME>
	<OUTCOME>NonSmoker</OUTCOME>
	<PROPERTY>position = (520, 79)</PROPERTY>
</VARIABLE>

<VARIABLE TYPE="nature">
	<NAME>Tuberculosis</NAME>
	<OUTCOME>Present</OUTCOME>
	<OUTCOME>Absent</OUTCOME>
	<PROPERTY>position = (166, 175)</PROPERTY>
</VARIABLE>

<VARIABLE TYPE="nature">
	<NAME>Cancer</NAME>
	<OUTCOME>Present</OUTCOME>
	<OUTCOME>Absent</OUTCOME>
	<PROPERTY>position = (418, 175)</PROPERTY>
</VARIABLE>

<VARIABLE TYPE="nature">
	<NAME>TbOrCa</NAME>
	<OUTCOME>True</OUTCOME>
	<OUTCOME>False</OUTCOME>
	<PROPERTY>position = (310, 271)</PROPERTY>
</VARIABLE>

<VARIABLE TYPE="nature">
	<NAME>XRay</NAME>
	<OUTCOME>Abnormal</OUTCOME>
	<OUTCOME>Normal</OUTCOME>
	<PROPERTY>position = (178, 361)</PROPERTY>
</VARIABLE>

<VARIABLE TYPE="nature">
	<NAME>Bronchitis</NAME>
	<OUTCOME>Present</OUTCOME>
	<OUTCOME>Absent</OUTCOME>
	<PROPERTY>position = (658, 175)</PROPERTY>
</VARIABLE>

<VARIABLE TYPE="nature">
	<NAME>Dyspnea</NAME>
	<OUTCOME>Present</OUTCOME>
	<OUTCOME>Absent</OUTCOME>
	<PROPERTY>position = (454, 361)</PROPERTY>
</VARIABLE>


<!-- Probabilitydistributions-->
<DEFINITION>
	<FOR>VisitAsia</FOR>
	<TABLE>0.01 0.99 </TABLE>
</DEFINITION>

<DEFINITION>
	<FOR>Smoking</FOR>
	<TABLE>0.49 0.51 </TABLE>
</DEFINITION>

<DEFINITION>
	<FOR>Tuberculosis</FOR>
	<TABLE>0.0090 0.991 </TABLE>
</DEFINITION>

<DEFINITION>
	<FOR>Cancer</FOR>
	<GIVEN>Smoking</GIVEN>
	<TABLE>0.12857142857142856 0.00980392156862745 0.8714285714285714 0.9901960784313726 </TABLE>
</DEFINITION>

<DEFINITION>
	<FOR>TbOrCa</FOR>
	<GIVEN>Cancer</GIVEN>
	<GIVEN>Tuberculosis</GIVEN>
	<TABLE>0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 </TABLE>
</DEFINITION>

<DEFINITION>
	<FOR>XRay</FOR>
	<GIVEN>TbOrCa</GIVEN>
	<TABLE>1.0 0.04225352112676056 0.0 0.9577464788732394 </TABLE>
</DEFINITION>

<DEFINITION>
	<FOR>Bronchitis</FOR>
	<GIVEN>Smoking</GIVEN>
	<TABLE>0.6224489795918368 0.32941176470588235 0.37755102040816324 0.6705882352941176 </TABLE>
</DEFINITION>

<DEFINITION>
	<FOR>Dyspnea</FOR>
	<GIVEN>Bronchitis</GIVEN>
	<GIVEN>TbOrCa</GIVEN>
	<GIVEN>Tuberculosis</GIVEN>
	<TABLE>0.5 0.9302325581395349 0.0 0.794392523364486 0.8571428571428571 0.56 0.0 0.11515151515151516 0.5 0.06976744186046512 0.0 0.205607476635514 0.14285714285714285 0.44 0.0 0.8848484848484849 </TABLE>
</DEFINITION>




</NETWORK>
</BIF>